[dogs]
name = 'DOG Serialization'
description = '''
A universal code generator based serialization library
with almost zero boilerplate.
'''
category = 'Serialization'
depends = []

[dogs.dependencies]
dogs_core = '^3.0.0'
dogs_darwin = '^1.0.1-alpha.5'

[dogs.devDependencies]
dogs_generator = '^2.1.2'

[dogs_yaml]
name = 'DOG Yaml'
description = '''
Yaml extension for the DOG serialization library.
'''
category = 'Serialization'
depends = ['dogs']

[dogs_yaml.dependencies]
dogs_yaml = '^2.0.3'

[dogs_yaml.devDependencies]

[dogs_toml]
name = 'DOG Toml'
description = '''
Toml extension for the DOG serialization library.
'''
category = 'Serialization'
depends = ['dogs']

[dogs_toml.dependencies]
dogs_toml = '^2.0.3'

[dogs_toml.devDependencies]

[dogs_cbor]
name = 'DOG Cbor'
description = '''
Cbor extension for the DOG serialization library.
'''
category = 'Serialization'
depends = ['dogs']

[dogs_cbor.dependencies]
dogs_cbor = '^2.0.3'

[dogs_cbor.devDependencies]

[drift]
name = 'DriftDB'
description = '''
Persistence library for dart using sql3.
'''
category = 'Database'
depends = []

[drift.dependencies]
drift = '^2.5.0'
sqlite3_flutter_libs = '^0.5.13'
path_provider = '^2.0.13'
path = '^1.8.3'

[drift.devDependencies]
drift_dev = '^2.5.2'

[mongodb]
name = 'MongoDB Driver'
description = '''
Server-side driver library for MongoDB.
'''
category = 'Database'
depends = []

[mongodb.dependencies]
mongo_dart = '^0.9.0'

[mongodb.devDependencies]

[mysql]
name = 'MySQL Driver'
description = '''
MySQL driver library based on SQLJocky.
'''
category = 'Database'
depends = []

[mysql.dependencies]
mysql1 = '^0.20.0'

[mysql.devDependencies]

[postgres]
name = 'PostgreSQL Driver'
description = '''
Postgres driver library.
'''
category = 'Database'
depends = []

[postgres.dependencies]
postgres = '^2.6.1'

[postgres.devDependencies]

[redis]
name = 'Redis Driver'
description = '''
Redis driver client library for dart.
'''
category = 'Database'
depends = []

[redis.dependencies]
redis = '^3.1.0'

[redis.devDependencies]

[dio]
name = 'DIO'
description = '''
A powerful http client library for dart.
'''
category = 'Web'
depends = []

[dio.dependencies]
dio = '^5.0.1'

[dio.devDependencies]

[websocket]
name = 'Web Socket Channel'
description = '''
Client library for connecting to web sockets.
'''
category = 'Web'
depends = []

[websocket.dependencies]
web_socket_channel = '^2.3.0'

[websocket.devDependencies]
