darwin_sdk = '^1.1.0-alpha.10'
darwin_eventbus = '^1.1.0-alpha.3'
darwin_injector = '^1.1.0-alpha.1'
darwin_gen = '^1.1.0-alpha.10'
darwin_marshal = '^1.1.0-alpha.11'
darwin_http = '^1.1.0-alpha.14'
darwin_http_gen = '^1.1.0-alpha.15'
logging = '^1.1.1'
lints = '^2.0.1'
test = '^1.16.0'
darwin_test = '^1.1.0-alpha.11'
build_runner = '^2.3.3'
