darwin_sdk = "^1.1.0-alpha.5"
darwin_eventbus = "^1.1.0-alpha.1"
darwin_injector = "^1.1.0-alpha.1"
darwin_gen = "^1.1.0-alpha.5"
darwin_marshal = "^1.1.0-alpha.6"
darwin_http = "^1.1.0-alpha.8"
darwin_http_gen = "^1.1.0-alpha.9"
logging = "^1.1.0"
lints = "^2.0.0"
test = "^1.16.0"
darwin_test = "^1.1.0-alpha.5"
build_runner = "^2.3.3"
